// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhNXmR5xqEZ8trbNdtoz7QjoWHfe3_D9I',
    appId: '1:539268712948:web:d3c2b3b61b83d7e5a911a1',
    messagingSenderId: '539268712948',
    projectId: 'huyphan-47e6b',
    authDomain: 'huyphan-47e6b.firebaseapp.com',
    storageBucket: 'huyphan-47e6b.firebasestorage.app',
    measurementId: 'G-VQS9F8PMQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbMdFPKbQzn8ARwSAFQIgrFA8Js4MPNw',
    appId: '1:539268712948:android:9e438af66b4a539ea911a1',
    messagingSenderId: '539268712948',
    projectId: 'huyphan-47e6b',
    storageBucket: 'huyphan-47e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgsEmDRXL3lmmA8qu1O5rBATmhGwbpyxg',
    appId: '1:539268712948:ios:b36d0f7d334c7bb5a911a1',
    messagingSenderId: '539268712948',
    projectId: 'huyphan-47e6b',
    storageBucket: 'huyphan-47e6b.firebasestorage.app',
    iosBundleId: 'com.example.huyphanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgsEmDRXL3lmmA8qu1O5rBATmhGwbpyxg',
    appId: '1:539268712948:ios:b36d0f7d334c7bb5a911a1',
    messagingSenderId: '539268712948',
    projectId: 'huyphan-47e6b',
    storageBucket: 'huyphan-47e6b.firebasestorage.app',
    iosBundleId: 'com.example.huyphanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhNXmR5xqEZ8trbNdtoz7QjoWHfe3_D9I',
    appId: '1:539268712948:web:321d46dee1e33736a911a1',
    messagingSenderId: '539268712948',
    projectId: 'huyphan-47e6b',
    authDomain: 'huyphan-47e6b.firebaseapp.com',
    storageBucket: 'huyphan-47e6b.firebasestorage.app',
    measurementId: 'G-F1TLH7NJH7',
  );
}
